name: Building and testing the first workflow

on:
  push

jobs: 
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the application
        run: g++ -Wall *.cpp -o a.out
      - name: Upload binary
        uses: actions/upload-artifact@v2
        with:
            name: application
            path: a.out
      - name : Run input - output tests
        run: ./a.out < input.txt >> generatedOutput.txt
      - name : Run input - output tests
        run: ./a.out < input2.txt >> generatedOutput2.txt
      - name : Run input - output tests
        run: ./a.out < input3.txt >> generatedOutput3.txt
      - name : Check result of input - output tests
        run: diff generatedOutput.txt expectedOutput.txt
      - name : Check result of input - output tests
        run: diff generatedOutput2.txt expectedOutput2.txt
      - name : Check result of input - output tests
        run: diff generatedOutput3.txt expectedOutput3.txt
      - name: Upload generated output
        uses: actions/upload-artifact@v2
        with:
          name: generated_output
          path: generatedOutput.txt
      - name: Upload generated output
        uses: actions/upload-artifact@v2
        with:
          name: generated_output2
          path: generatedOutput2.txt
      - name: Upload generated output
        uses: actions/upload-artifact@v2
        with:
          name: generated_output3
          path: generatedOutput3.txt
